sonar.projectKey=OneCommunityGlobal_HGNRest
sonar.organization=onecommunityglobal

sonar.sources=src
sonar.exclusions=**/node_modules/**,**/coverage/**,**/dist/**,**/build/**,**/*.test.js,**/*.spec.js,**/test/**,**/__tests__/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info