const UTILIZATION_THRESHOLDS = {
  UNDER_UTILIZED_MAX: 55,
  NORMAL_MAX: 85,
};

const UTILIZATION_LABELS = {
  UNDER: 'Under-utilized',
  NORMAL: 'Normal',
  OVER: 'Over-utilized',
};

const TRAFFIC_LIGHT = {
  GREEN: 'green',
  YELLOW: 'yellow',
  RED: 'red',
};

const FORECAST_MODES = {
  HISTORICAL: 'historical',
  FORECAST_30: 'forecast30',
  FORECAST_FULL: 'forecastFull',
};

const VALID_FORECAST_MODES = Object.values(FORECAST_MODES);

const REPORT_FORMATS = ['pdf', 'csv'];

const MAINTENANCE_TRIGGER_THRESHOLD = 85;

const MINIMUM_WEEKS_FOR_REGRESSION = 3;

const FORECAST_DEFAULT_DAYS = 30;

const HOURS_PER_DAY = 24;
const DAYS_PER_WEEK = 7;
const MS_PER_HOUR = 3600000;

const DEGRADED_CONDITIONS = ['Worn', 'Needs Repair', 'Needs Replacing'];
const NON_OPERATIONAL_STATUSES = ['Under Maintenance', 'Out of Service'];

const CONFIDENCE_THRESHOLDS = {
  HIGH: 0.7,
  MEDIUM: 0.4,
};

const ENSEMBLE_WEIGHTS = {
  HIGH_R2: { regression: 0.6, ema: 0.4 },
  MEDIUM_R2: { regression: 0.4, ema: 0.6 },
  LOW_R2: { regression: 0.2, ema: 0.8 },
};

const EMA_SMOOTHING_BASE = 2;

const ROUNDING_PRECISION = 10;
const PDF_MOVE_DOWN_HALF = 0.5;

const PDF_STYLES = {
  FONT_SIZE_TITLE: 24,
  FONT_SIZE_METADATA: 10,
  FONT_SIZE_SECTION_HEADER: 16,
  FONT_SIZE_BODY: 11,
  FONT_SIZE_DETAIL: 10,
  PAGE_BREAK_THRESHOLD: 700,
  PAGE_MARGIN: 50,
};

module.exports = {
  UTILIZATION_THRESHOLDS,
  UTILIZATION_LABELS,
  TRAFFIC_LIGHT,
  FORECAST_MODES,
  VALID_FORECAST_MODES,
  REPORT_FORMATS,
  MAINTENANCE_TRIGGER_THRESHOLD,
  MINIMUM_WEEKS_FOR_REGRESSION,
  FORECAST_DEFAULT_DAYS,
  HOURS_PER_DAY,
  DAYS_PER_WEEK,
  MS_PER_HOUR,
  DEGRADED_CONDITIONS,
  NON_OPERATIONAL_STATUSES,
  CONFIDENCE_THRESHOLDS,
  ENSEMBLE_WEIGHTS,
  EMA_SMOOTHING_BASE,
  ROUNDING_PRECISION,
  PDF_MOVE_DOWN_HALF,
  PDF_STYLES,
};
